FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    iptables \
    iproute2 \
    iputils-ping \
    net-tools \
    iptables-persistent

COPY firewall_rules.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/firewall_rules.sh

CMD ["/usr/local/bin/firewall_rules.sh"]